<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Productype extends Model
{
	protected $table = "type_products";

	public function product(){
		return $this->hasMany('App\product','id_type','id');
	}

	public function delete()
    {
        $this->product()->delete();
        return parent::delete(); // TODO: Change the autogenerated stub
    }
    //
}
